export enum WsResponseAction {
  KEEPER_DENY_ACCESS_WITH_WRONG_PLATE_TICKET = 'KEEPER_DENY_ACCESS_WITH_WRONG_PLATE_TICKET',
  KEEPER_DENY_ACCESS_WITH_WRONG_PLATE_MEMBER = 'KEEPER_DENY_ACCESS_WITH_WRONG_PLATE_MEMBER',
  KEEPER_APPROVE_ACCESS_WITH_WRONG_PLATE_TICKET = 'KEEPER_APPROVE_ACCESS_WITH_WRONG_PLATE_TICKET',
  KEEPER_APPROVE_ACCESS_WITH_WRONG_PLATE_MEMBER = 'KEEPER_APPROVE_ACCESS_WITH_WRONG_PLATE_MEMBER',
}
